src/main/scala/nl/knaw/dans/easy/fedora2vault/Command.scala, src/main/scala/nl/knaw/dans/easy/fedora2vault/EasyFedora2vaultApp.scala, src/test/scala/nl/knaw/dans/easy/fedora2vault/AppSpec.scala
Fixes EASY-2680: simpleTransform for multiple datasets
* 
* 
* 
Build deploy on deasy, then:
```
rm -rf /vagrant/shared/f2vbags
easy-fedora2vault -i /vagrant/shared/f2v.txt -o /vagrant/shared/f2vbags simple
```
With datasets IDs in `/vagrant/shared/f2v.txt` (note that 10 is omitted because of a large and hence slow interview):
```
easy-dataset:1
easy-dataset:2
easy-dataset:3
easy-dataset:4
easy-dataset:5
easy-dataset:6
easy-dataset:7
easy-dataset:8
easy-dataset:9
easy-dataset:11
easy-dataset:12
easy-dataset:13
easy-dataset:14
easy-dataset:15
easy-dataset:16
easy-dataset:17
```
Will cause (easy to merge?) conflicts with #2
=> EASY-2680: simpleTransform for multiple datasets

src/main/scala/nl/knaw/dans/easy/fedora2vault/EasyFedora2vaultApp.scala, src/main/scala/nl/knaw/dans/easy/fedora2vault/FileMetadata.scala, src/main/scala/nl/knaw/dans/easy/fedora2vault/FoXml.scala, src/test/scala/nl/knaw/dans/easy/fedora2vault/AppSpec.scala
Fixes EASY-2678 create files.xml
* 
* 
* 
see #4 then
`grep '>' /vagrant/shared/f2vbags/*/metadata/files.xml`
=> EASY-2678 create files.xml

docs/index.md, src/main/scala/nl/knaw/dans/easy/fedora2vault/CommandLineOptions.scala
NO EASY
* Add 'strict' rules to readme
* Remove -f option from readme
* Add description of output logfile
=> NO-JIRA: Remove file-metadata option from commandline

src/main/scala/nl/knaw/dans/easy/fedora2vault/BagIndex.scala, src/main/scala/nl/knaw/dans/easy/fedora2vault/Command.scala, src/main/scala/nl/knaw/dans/easy/fedora2vault/CommandLineOptions.scala, src/main/scala/nl/knaw/dans/easy/fedora2vault/CsvRecord.scala, src/main/scala/nl/knaw/dans/easy/fedora2vault/EasyFedora2vaultApp.scala, src/main/scala/nl/knaw/dans/easy/fedora2vault/SimpleChecker.scala, src/test/scala/nl/knaw/dans/easy/fedora2vault/AppSpec.scala, src/test/scala/nl/knaw/dans/easy/fedora2vault/BagIndexSpec.scala, src/test/scala/nl/knaw/dans/easy/fedora2vault/SimpleCheckerSpec.scala, src/test/scala/nl/knaw/dans/easy/fedora2vault/fixture/TestSupportFixture.scala
Fixes EASY-2732 check strict only when specified
* no more null pointer exception when omitting the mandatory -o argument
* examines what the bag-index returns between `<result></result>`
* verbose rule violation comment field
https://github.com/DANS-KNAW/easy-fedora2vault/blob/b4ed821f665e59b123bebedfe24f2deb47717261/src/test/scala/nl/knaw/dans/easy/fedora2vault/SimpleCheckerSpec.scala#L108
* verbose feedback message `no fedora/IO errors, for details see /path/to/xxx.csv`
https://github.com/DANS-KNAW/easy-fedora2vault/blob/bda05b2ab6647bddd56252b85913fac015beb1e8/src/test/scala/nl/knaw/dans/easy/fedora2vault/AppSpec.scala#L74
completed with
https://github.com/DANS-KNAW/easy-fedora2vault/blob/bda05b2ab6647bddd56252b85913fac015beb1e8/src/main/scala/nl/knaw/dans/easy/fedora2vault/Command.sca …
=> EASY-2732 check strict only when specified

src/main/scala/nl/knaw/dans/easy/fedora2vault/DDM.scala, src/main/scala/nl/knaw/dans/easy/fedora2vault/EasyFedora2vaultApp.scala, src/main/scala/nl/knaw/dans/easy/fedora2vault/Spatial.scala, src/test/scala/nl/knaw/dans/easy/fedora2vault/DdmSpec.scala
Fixes EASY-2744: EMD -> DDM spatial fields
We assume not, report as not implemented when practice proofs otherwise.
=> EASY-2744: EMD -> DDM spatial fields

docs/index.md, pom.xml, src/main/assembly/dist/cfg/application.properties, src/main/scala/nl/knaw/dans/easy/fedora2vault/Command.scala, src/main/scala/nl/knaw/dans/easy/fedora2vault/CommandLineOptions.scala, src/main/scala/nl/knaw/dans/easy/fedora2vault/Configuration.scala, src/main/scala/nl/knaw/dans/easy/fedora2vault/CsvRecord.scala, src/main/scala/nl/knaw/dans/easy/fedora2vault/DepositProperties.scala, src/main/scala/nl/knaw/dans/easy/fedora2vault/EasyFedora2vaultApp.scala, src/main/scala/nl/knaw/dans/easy/fedora2vault/OutputFormat.scala, src/main/scala/nl/knaw/dans/easy/fedora2vault/TransformationType.scala, src/main/scala/nl/knaw/dans/easy/fedora2vault/check/SimpleChecker.scala, src/main/scala/nl/knaw/dans/easy/fedora2vault/check/ThemaChecker.scala, src/main/scala/nl/knaw/dans/easy/fedora2vault/filter/BagIndex.scala, src/main/scala/nl/knaw/dans/easy/fedora2vault/filter/Filter.scala, src/main/scala/nl/knaw/dans/easy/fedora2vault/filter/SimpleFilter.scala, src/main/scala/nl/knaw/dans/easy/fedora2vault/filter/TargetIndex.scala, src/main/scala/nl/knaw/dans/easy/fedora2vault/filter/ThemaFilter.scala, src/test/resources/debug-config/application.properties, src/test/scala/nl/knaw/dans/easy/fedora2vault/AppSpec.scala, src/test/scala/nl/knaw/dans/easy/fedora2vault/BagIndexSpec.scala, src/test/scala/nl/knaw/dans/easy/fedora2vault/DdmSpec.scala, src/test/scala/nl/knaw/dans/easy/fedora2vault/FilterSpec.scala, src/test/scala/nl/knaw/dans/easy/fedora2vault/ReadmeSpec.scala
Fixes DD-112: enable deposit-dir export
* have a new command line argument `--output-format` (short `-f`), values: `AIP` or `SIP`
* not check for existence in the vault in case of SIP, so strict mode is possible
* have a new application.property: `staging.dir`
for example for datasets that don't exist or are not simple while strict was specified~~
Functional
* The new Unit test AppSpec.simpleSips
~~Perhaps~~ a separate pull request?
Rafactored:
* renamed `check` methods/package to `filter`s
* moved `BagIndex` to `filter` package
* renamed simpleTransform(s) -> createSips/createAips/createBag, reduced chain of methods
* signatures of the renamed methods also changed
requires for deploy
* [-] ~~dd-dtap~~
=> DD-112: enable deposit-dir export

src/main/scala/nl/knaw/dans/easy/fedoratobag/FileItem.scala, src/test/scala/nl/knaw/dans/easy/fedoratobag/FileItemSpec.scala
Fixes EASY-2789: mapping of key-value pairs in files.xml
* 
* 
* 
=> EASY-2789: mapping of key-value pairs in files.xml

docs/index.md, src/main/scala/nl/knaw/dans/easy/fedoratobag/Command.scala, src/main/scala/nl/knaw/dans/easy/fedoratobag/CsvRecord.scala, src/main/scala/nl/knaw/dans/easy/fedoratobag/DatasetInfo.scala, src/main/scala/nl/knaw/dans/easy/fedoratobag/EasyFedoraToBagApp.scala, src/main/scala/nl/knaw/dans/easy/fedoratobag/FileFilterType.scala, src/main/scala/nl/knaw/dans/easy/fedoratobag/Options.scala, src/main/scala/nl/knaw/dans/easy/fedoratobag/TransformationType.scala, src/test/scala/nl/knaw/dans/easy/fedoratobag/AppSpec.scala, src/test/scala/nl/knaw/dans/easy/fedoratobag/CreateExportSpec.scala, src/test/scala/nl/knaw/dans/easy/fedoratobag/fixture/FileFoXmlSupport.scala
Fixes DD-208: Versioning with only original files in first bag
* 
https://github.com/DANS-KNAW/easy-fedora-to-bag/blob/fb6a7ac6ea3fcabb39262fd1711a300359dec2bc/src/test/scala/nl/knaw/dans/easy/fedoratobag/AppSpec.scala#L58
should produce (with other UUIDs):
```
target/test/AppSpec/output
|-- 448501b8-bb0c-4f52-9b0f-91ffc17ee1f8
|   `-- 15438c3f-4088-4f5c-b6de-3a20e8b27196
|       |-- bag-info.txt
|       |-- bagit.txt
|       |-- data
|       |   |-- original
|       |   |   `-- something.txt
|       |   `-- x
|       |       `-- something.txt
|       |-- manifest-sha1.txt
|       |-- metadata
|       |   |-- amd.xml
|       |   |-- dataset.xml
|       |   |-- emd.xml
|       |   |-- files.xml
|       |   `-- license.pdf
|       `-- tagmanifest-sha1.txt
`-- …
```
=> DD-208: Versioning with only original files in first bag 

docs/index.md, src/main/scala/nl/knaw/dans/easy/fedoratobag/Command.scala, src/main/scala/nl/knaw/dans/easy/fedoratobag/DatasetInfo.scala, src/main/scala/nl/knaw/dans/easy/fedoratobag/EasyFedoraToBagApp.scala, src/main/scala/nl/knaw/dans/easy/fedoratobag/TransformationType.scala, src/test/scala/nl/knaw/dans/easy/fedoratobag/AppSpec.scala, src/test/scala/nl/knaw/dans/easy/fedoratobag/CreateExportSpec.scala
Fixes DD-255: doi like urn via bag-info.txt
* 
* 
* 
See related PR
https://github.com/DANS-KNAW/easy-convert-bag-to-deposit/pull/10
=> DD-255: doi like urn via bag-info.txt

src/main/scala/nl/knaw/dans/easy/fedoratobag/Command.scala, src/main/scala/nl/knaw/dans/easy/fedoratobag/CsvRecord.scala, src/main/scala/nl/knaw/dans/easy/fedoratobag/DatasetInfo.scala, src/main/scala/nl/knaw/dans/easy/fedoratobag/EasyFedoraToBagApp.scala, src/main/scala/nl/knaw/dans/easy/fedoratobag/Options.scala, src/main/scala/nl/knaw/dans/easy/fedoratobag/VersionInfo.scala, src/main/scala/nl/knaw/dans/easy/fedoratobag/filter/DatasetFilter.scala, src/main/scala/nl/knaw/dans/easy/fedoratobag/filter/FedoraVersionedFilter.scala, src/main/scala/nl/knaw/dans/easy/fedoratobag/filter/SequenceFilter.scala, src/main/scala/nl/knaw/dans/easy/fedoratobag/versions/FedoraVersions.scala, src/test/resources/logback.xml, src/test/scala/nl/knaw/dans/easy/fedoratobag/AppSpec.scala, src/test/scala/nl/knaw/dans/easy/fedoratobag/CreateExportSpec.scala, src/test/scala/nl/knaw/dans/easy/fedoratobag/CreateSequenceSpec.scala, src/test/scala/nl/knaw/dans/easy/fedoratobag/DatasetFilterSpec.scala, src/test/scala/nl/knaw/dans/easy/fedoratobag/fixture/DelegatingApp.scala, src/test/scala/nl/knaw/dans/easy/fedoratobag/versions/FedoraVersionsSpec.scala
Fixes DD-210 fedora versioned - export the result of a dry run
and fixes check on jum-off pages
`CreateSequenceSpec`
Browse through Spec classes searching for `easyDatasetId,uuid1,uuid2,doi,depositor,transformationType,comment` to see possible results.
=> DD-210 fedora versioned - export the result of a dry run

src/main/scala/nl/knaw/dans/easy/fedoratobag/DDM.scala, src/main/scala/nl/knaw/dans/easy/fedoratobag/FedoraProvider.scala, src/test/scala/nl/knaw/dans/easy/fedoratobag/DdmSpec.scala
Fixes EASY-2813: only one title in ddm-profile
* further titles become an alternative title
* drop(1) is a safe alternative for tail
* 
=> EASY-2813: only one title in ddm-profile

src/main/scala/nl/knaw/dans/easy/fedoratobag/DDM.scala, src/test/scala/nl/knaw/dans/easy/fedoratobag/DdmSpec.scala
Fixes EASY-2810 not implemented ddm relation
* 
* 
* 
=> EASY-2810 not implemented ddm relation

src/main/scala/nl/knaw/dans/easy/fedoratobag/EasyFedoraToBagApp.scala, src/main/scala/nl/knaw/dans/easy/fedoratobag/FedoraProvider.scala, src/main/scala/nl/knaw/dans/easy/fedoratobag/FileInfo.scala, src/main/scala/nl/knaw/dans/easy/fedoratobag/FileItem.scala, src/main/scala/nl/knaw/dans/easy/fedoratobag/Options.scala, src/main/scala/nl/knaw/dans/easy/fedoratobag/filter/FileFilterType.scala, src/main/scala/nl/knaw/dans/easy/fedoratobag/filter/package.scala, src/main/scala/nl/knaw/dans/easy/fedoratobag/versions/FedoraVersions.scala, src/test/scala/nl/knaw/dans/easy/fedoratobag/AppSpec.scala, src/test/scala/nl/knaw/dans/easy/fedoratobag/FileItemSpec.scala, src/test/scala/nl/knaw/dans/easy/fedoratobag/fixture/DelegatingApp.scala
Fixes
* DD-208: original versioned: without original level in file paths
* EASY-2808: report duplicated files as an error
* 
* 
* 
=> DD-208, EASY-2808: original versioned without original, handling duplicated files

docs/index.md, src/main/scala/nl/knaw/dans/easy/fedoratobag/BagVersion.scala, src/main/scala/nl/knaw/dans/easy/fedoratobag/Command.scala, src/main/scala/nl/knaw/dans/easy/fedoratobag/CommandLineOptions.scala, src/main/scala/nl/knaw/dans/easy/fedoratobag/DatasetInfo.scala, src/main/scala/nl/knaw/dans/easy/fedoratobag/EasyFedoraToBagApp.scala, src/main/scala/nl/knaw/dans/easy/fedoratobag/filter/DatasetFilter.scala, src/main/scala/nl/knaw/dans/easy/fedoratobag/package.scala, src/main/scala/nl/knaw/dans/easy/fedoratobag/versions/EmdVersionInfo.scala, src/main/scala/nl/knaw/dans/easy/fedoratobag/versions/FedoraVersions.scala, src/test/resources/logback.xml, src/test/scala/nl/knaw/dans/easy/fedoratobag/AppSpec.scala, src/test/scala/nl/knaw/dans/easy/fedoratobag/CreateExportSpec.scala, src/test/scala/nl/knaw/dans/easy/fedoratobag/fixture/DelegatingApp.scala, src/test/scala/nl/knaw/dans/easy/fedoratobag/versions/BagVersionSpec.scala, src/test/scala/nl/knaw/dans/easy/fedoratobag/versions/EmdVersionSpec.scala, src/test/scala/nl/knaw/dans/easy/fedoratobag/versions/FedoraVersionsSpec.scala
Fixes DD-343: fedora versions not properly assembled
* have some classes refactored
* additional logging following the analysis of dataset families
* 
=> DD-343: fedora versions not properly assembled

src/main/scala/nl/knaw/dans/easy/fedoratobag/DDM.scala, src/test/scala/nl/knaw/dans/easy/fedoratobag/DdmSpec.scala
Fixes DD-395: date precision for created/available
* `<eas:date>` is corrected (time zone + too big year)
* `<dct:date>` is copied as-is
* 
=> DD-395: date precision for created/available

src/main/scala/nl/knaw/dans/easy/fedoratobag/FileInfo.scala, src/test/scala/nl/knaw/dans/easy/fedoratobag/FileInfosSpec.scala
Fixes DD-342
* replace `non allowed characters` (in Dataverse) in `filenames`
* does the same for `filepaths`
Non allowed characters are: ':', '*', '?', '"', '<', '>', '|', ';', '#'
**Notice**: In the Jira issue only `filename` is mentioned.  I assume that the same restriction in Dataverse applies also to `filepath`. **Correct?** 
=> DD-342: No special chars in filenames

src/main/scala/nl/knaw/dans/easy/fedoratobag/EasyFedoraToBagApp.scala, src/main/scala/nl/knaw/dans/easy/fedoratobag/package.scala, src/test/resources/sample-foxml/DepositApi.xml, src/test/scala/nl/knaw/dans/easy/fedoratobag/AppSpec.scala, src/test/scala/nl/knaw/dans/easy/fedoratobag/DdmSpec.scala, src/test/scala/nl/knaw/dans/easy/fedoratobag/fixture/EmdSupport.scala
Fixes DD-412: preserve white space in XML
* preserve white space in the DDM
* **NB** unit tests that assemble a custom EMD don't preserve white space, see commit with quick and dirty fix
* 
=> DD-412: preserve white space in XML

src/main/scala/nl/knaw/dans/easy/fedoratobag/EasyFedoraToBagApp.scala, src/main/scala/nl/knaw/dans/easy/fedoratobag/FileInfo.scala, src/main/scala/nl/knaw/dans/easy/fedoratobag/package.scala, src/test/scala/nl/knaw/dans/easy/fedoratobag/AppSpec.scala, src/test/scala/nl/knaw/dans/easy/fedoratobag/DdmSpec.scala, src/test/scala/nl/knaw/dans/easy/fedoratobag/FileInfosSpec.scala, src/test/scala/nl/knaw/dans/easy/fedoratobag/fixture/FileFoXmlSupport.scala
Fixes DD-396: prevent identical original-versioned bags
* prevent identical original-versioned bags when both have the same set of files that only differ by (one of)`fedoraFileId, accessibleTo, visibleTo`
* whenever there would have been identical bags, the files will get all properties from the second bag
* whenever there are two bags, they both may still have files that are only different by the properties above
The new unit test in AppSpec
=> DD-396: prevent identical original-versioned bags

docs/index.md, src/main/scala/nl/knaw/dans/easy/fedoratobag/Command.scala, src/main/scala/nl/knaw/dans/easy/fedoratobag/CommandLineOptions.scala, src/main/scala/nl/knaw/dans/easy/fedoratobag/EasyFedoraToBagApp.scala, src/main/scala/nl/knaw/dans/easy/fedoratobag/Options.scala, src/main/scala/nl/knaw/dans/easy/fedoratobag/filter/package.scala, src/test/scala/nl/knaw/dans/easy/fedoratobag/FileInfosSpec.scala
Fixes DD-429: new option: no payload
* no unit test is added yet
* 
* 
deploy and run on deasy:
easy-fedora-to-bag -p -d 'easy-dataset:9' -o /vagrant/shared/xxx -f SIP simple
=> DD-429: new option: no payload

src/main/scala/nl/knaw/dans/easy/fedoratobag/EasyFedoraToBagApp.scala, src/main/scala/nl/knaw/dans/easy/fedoratobag/FedoraProvider.scala, src/main/scala/nl/knaw/dans/easy/fedoratobag/FileInfo.scala, src/main/scala/nl/knaw/dans/easy/fedoratobag/FileItem.scala, src/main/scala/nl/knaw/dans/easy/fedoratobag/FoXml.scala, src/test/scala/nl/knaw/dans/easy/fedoratobag/AppSpec.scala, src/test/scala/nl/knaw/dans/easy/fedoratobag/FileInfosSpec.scala, src/test/scala/nl/knaw/dans/easy/fedoratobag/FileItemSpec.scala, src/test/scala/nl/knaw/dans/easy/fedoratobag/fixture/FileFoXmlSupport.scala
Fixes DD-447: was derived from
* add `<dct:source>` to `files.xml` based on `<wasDerivedFrom ... rdf:resource=...>` in RELS-EXT of file foXML
* 
* 
=> DD-447: was derived from

docs/index.md, src/main/scala/nl/knaw/dans/easy/fedoratobag/Command.scala, src/main/scala/nl/knaw/dans/easy/fedoratobag/CommandLineOptions.scala, src/main/scala/nl/knaw/dans/easy/fedoratobag/CsvRecord.scala, src/main/scala/nl/knaw/dans/easy/fedoratobag/DDM.scala, src/main/scala/nl/knaw/dans/easy/fedoratobag/DatasetInfo.scala, src/main/scala/nl/knaw/dans/easy/fedoratobag/EasyFedoraToBagApp.scala, src/main/scala/nl/knaw/dans/easy/fedoratobag/Options.scala, src/test/scala/nl/knaw/dans/easy/fedoratobag/AppSpec.scala, src/test/scala/nl/knaw/dans/easy/fedoratobag/CreateExportSpec.scala, src/test/scala/nl/knaw/dans/easy/fedoratobag/CreateSequenceSpec.scala
Fixes DD-523: no payload for datasets with more than X files
* 
* 
run for all deasy datasets with `-c 3`. One of the CSV lines is something like 
easy-dataset:12,<UUID>,,<DOI>,user001,fedora-versioned,"OK; no payload, nr of files exceeds 3"
The log contains something like :
[2021-06-28 15:04:38,306] INFO  Creating /... from easy-dataset:12 with owner user001
[2021-06-28 15:04:38,351] WARN  too many files 12, 0
=> DD-523: no payload for datasets with more than X files

src/main/scala/nl/knaw/dans/easy/fedoratobag/FileItem.scala
NO EASY
* Replace -- in xml comment block. this is a forbidden char combination in an xml comment
=> Replace -- in xml comment block

src/main/scala/nl/knaw/dans/easy/fedoratobag/DDM.scala, src/main/scala/nl/knaw/dans/easy/fedoratobag/EasyFedoraToBagApp.scala, src/test/scala/nl/knaw/dans/easy/fedoratobag/AppSpec.scala, src/test/scala/nl/knaw/dans/easy/fedoratobag/DdmSpec.scala
Fixes DD-585
* throw an exception when there is `not:implemented` node in the DDM
=> DD-585: not:implemented should result in FAILED

src/main/scala/nl/knaw/dans/easy/fedoratobag/filter/DatasetFilter.scala, src/test/scala/nl/knaw/dans/easy/fedoratobag/DatasetFilterSpec.scala
Fixes DD-578
* Remove rule 2 ("`has jump off`") from easy-fedora-to-bag `violations`
* 
* 
=> DD-578: Remove Rule 2 from easy-fedora-to-bag violations

src/main/scala/nl/knaw/dans/easy/fedoratobag/DDM.scala, src/test/scala/nl/knaw/dans/easy/fedoratobag/DdmSpec.scala
Fixes DD-598
* add `protocol http` to uri's that start with `www`
=> DD-598: protocol 'null' in URI

src/main/assembly/dist/cfg/application.properties, src/main/scala/nl/knaw/dans/easy/fedoratobag/Configuration.scala, src/main/scala/nl/knaw/dans/easy/fedoratobag/EasyFedoraToBagApp.scala, src/main/scala/nl/knaw/dans/easy/fedoratobag/filter/DatasetFilter.scala, src/test/resources/debug-config/application.properties, src/test/scala/nl/knaw/dans/easy/fedoratobag/AppSpec.scala, src/test/scala/nl/knaw/dans/easy/fedoratobag/DatasetFilterSpec.scala, src/test/scala/nl/knaw/dans/easy/fedoratobag/ReadmeSpec.scala, src/test/scala/nl/knaw/dans/easy/fedoratobag/fixture/DelegatingApp.scala
Fixes DD-586
* make `states`, that are to be exported, `configurable`
=> DD-586: Make 'state' to be exported configurable

src/main/scala/nl/knaw/dans/easy/fedoratobag/EasyFedoraToBagApp.scala, src/test/scala/nl/knaw/dans/easy/fedoratobag/AppSpec.scala
Fixes DD-639
* Add depositor-info/agreements.xml to second bag
=> DD-639: Add depositor-info/agreements.xml to second bag

src/main/scala/nl/knaw/dans/easy/fedoratobag/EasyFedoraToBagApp.scala, src/main/scala/nl/knaw/dans/easy/fedoratobag/FileInfo.scala, src/main/scala/nl/knaw/dans/easy/fedoratobag/filter/DatasetFilter.scala, src/test/scala/nl/knaw/dans/easy/fedoratobag/AppSpec.scala, src/test/scala/nl/knaw/dans/easy/fedoratobag/DatasetFilterSpec.scala
Fixes DD-665 pick one file in case of duplicates
* 
* 
=> DD-655 pick one file in case of duplicates

src/main/scala/nl/knaw/dans/easy/fedoratobag/EasyFedoraToBagApp.scala, src/main/scala/nl/knaw/dans/easy/fedoratobag/filter/package.scala, src/test/scala/nl/knaw/dans/easy/fedoratobag/AppSpec.scala, src/test/scala/nl/knaw/dans/easy/fedoratobag/FileInfosSpec.scala
Fixes DD-636
* throw `NoPayloadFilesException` only when in `strict mode`, otherwise only warning
=> DD-636: Allow datasets with NoPayload

src/main/scala/nl/knaw/dans/easy/fedoratobag/DDM.scala
=> DD-945: String.isBlank is not safe between JDK-8/11

src/main/scala/nl/knaw/dans/easy/fedoratobag/EasyFedoraToBagApp.scala
replaces #98
* gets rid of the confusing negative test
* `noPayload` / `skipPayload` avoid collision in the same name space
* more files than the `cutoff` is treated as `noPayload`
* 
* Please compile with JDK-8 because of jibx:
export JAVA_HOME=`/usr/libexec/java_home -v 1.8`
They suggest the dataset has no payload  while the command line options might have specified to skip the payload, either through a `cutoff` or with `noPayload`.
export JAVA_HOME=`/usr/libexec/java_home -v 1.8`
* ...
=> NO JIRA ISSUE: rename 

src/main/scala/nl/knaw/dans/easy/fedoratobag/EasyFedoraToBagApp.scala, src/main/scala/nl/knaw/dans/easy/fedoratobag/filter/DatasetFilter.scala, src/test/scala/nl/knaw/dans/easy/fedoratobag/AppSpec.scala, src/test/scala/nl/knaw/dans/easy/fedoratobag/DatasetFilterSpec.scala, src/test/scala/nl/knaw/dans/easy/fedoratobag/versions/ResolverSpec.scala
Fixes DD-769: nopayload exception turned into a rule violation
* 
* 
* 
* Please compile with JDK-8 because of jibx:
export JAVA_HOME=`/usr/libexec/java_home -v 1.8`
* ...
=> DD-769: nopayload exception changed into a rule violation

src/main/scala/nl/knaw/dans/easy/fedoratobag/EasyFedoraToBagApp.scala, src/test/scala/nl/knaw/dans/easy/fedoratobag/AppSpec.scala
Fixes DD-1239
* 
* 
* 
* Please compile with JDK-8 because of jibx:
export JAVA_HOME=`/usr/libexec/java_home -v 1.8`
* ...
export JAVA_HOME=`/usr/libexec/java_home -v 1.8`
* ...
=> DD-1239: Point migration-link to description tab in EASY

pom.xml, src/main/scala/nl/knaw/dans/easy/fedoratobag/EasyFedoraToBagApp.scala, src/main/scala/nl/knaw/dans/easy/fedoratobag/FileInfo.scala, src/main/scala/nl/knaw/dans/easy/fedoratobag/FileItem.scala, src/test/resources/sample-foxml/invalidUrl.xml, src/test/scala/nl/knaw/dans/easy/fedoratobag/AppSpec.scala, src/test/scala/nl/knaw/dans/easy/fedoratobag/FileInfosSpec.scala, src/test/scala/nl/knaw/dans/easy/fedoratobag/FileItemSpec.scala, src/test/scala/nl/knaw/dans/easy/fedoratobag/fixture/FileFoXmlSupport.scala
Fixes EASY-DD-1558 av location url
* see commits
* 
* 
* Please compile with JDK-8 because of jibx:
export JAVA_HOME=`/usr/libexec/java_home -v 1.8`
* ...
export JAVA_HOME=`/usr/libexec/java_home -v 1.8`
* ...
=> DD-1558 av location url
