- src/main/scala/nl/knaw/dans/easy/fedora2vault/EasyFedora2vaultApp.scala
- src/main/scala/nl/knaw/dans/easy/fedora2vault/FileItem.scala
- src/main/scala/nl/knaw/dans/easy/fedora2vault/FoXml.scala
- src/test/resources/sample-foxml/easy-file-35.xml
- src/test/scala/nl/knaw/dans/easy/fedora2vault/AppSpec.scala
Fixes EASY-2723 sha check of payload files
* 
* 
* 
> EASY-2723 sha check of payload files

- src/main/scala/nl/knaw/dans/easy/fedora2vault/DDM.scala
- src/main/scala/nl/knaw/dans/easy/fedora2vault/FileItem.scala
Fixes Review with datamanageer
* 
* 
* 
> noJira issue: Review with datamanageer

- src/main/scala/nl/knaw/dans/easy/fedora2vault/DDM.scala
- src/main/scala/nl/knaw/dans/easy/fedora2vault/EasyFedora2vaultApp.scala
- src/test/scala/nl/knaw/dans/easy/fedora2vault/DdmSpec.scala
- src/test/scala/nl/knaw/dans/easy/fedora2vault/fixture/EmdSupport.scala
Fixes EASY-2475: emd2ddm the final bits and pieces
* 
* 
* 
> EASY-2475: emd2ddm the final bits and pieces

- docs/index.md
- src/main/scala/nl/knaw/dans/easy/fedora2vault/Command.scala
- src/main/scala/nl/knaw/dans/easy/fedora2vault/CommandLineOptions.scala
- src/main/scala/nl/knaw/dans/easy/fedora2vault/EasyFedora2vaultApp.scala
- src/main/scala/nl/knaw/dans/easy/fedora2vault/TransformationType.scala
- src/main/scala/nl/knaw/dans/easy/fedora2vault/check/SimpleChecker.scala
- src/main/scala/nl/knaw/dans/easy/fedora2vault/check/ThemaChecker.scala
- src/main/scala/nl/knaw/dans/easy/fedora2vault/check/TransformationChecker.scala
- src/main/scala/nl/knaw/dans/easy/fedora2vault/package.scala
- src/test/scala/nl/knaw/dans/easy/fedora2vault/AppSpec.scala
- src/test/scala/nl/knaw/dans/easy/fedora2vault/TransformationCheckerSpec.scala
Fixes EASY-
* 
* 
* 
The new trailing argument description in `docs/index.md`
> EASY-2413 new transformation for "thematische collecties"

- src/main/scala/nl/knaw/dans/easy/fedora2vault/BagIndex.scala
- src/test/scala/nl/knaw/dans/easy/fedora2vault/AppSpec.scala
- src/test/scala/nl/knaw/dans/easy/fedora2vault/BagIndexSpec.scala
- src/test/scala/nl/knaw/dans/easy/fedora2vault/DdmSpec.scala
- src/test/scala/nl/knaw/dans/easy/fedora2vault/DebugConfigSpec.scala
- src/test/scala/nl/knaw/dans/easy/fedora2vault/TransformationCheckerSpec.scala
- src/test/scala/nl/knaw/dans/easy/fedora2vault/fixture/BagIndexSupport.scala
Fixes EASY-
* eliminated todo's
* additional tests for transformer variants
* 
> NO JIRA ISSUE: clean up

- src/main/scala/nl/knaw/dans/easy/fedoratobag/AbrMappings.scala
- src/main/scala/nl/knaw/dans/easy/fedoratobag/CommandLineOptions.scala
- src/main/scala/nl/knaw/dans/easy/fedoratobag/Configuration.scala
- src/main/scala/nl/knaw/dans/easy/fedoratobag/DDM.scala
- src/main/scala/nl/knaw/dans/easy/fedoratobag/EasyFedora2vaultApp.scala
- src/main/scala/nl/knaw/dans/easy/fedoratobag/FileItem.scala
- src/test/scala/nl/knaw/dans/easy/fedoratobag/AppSpec.scala
- src/test/scala/nl/knaw/dans/easy/fedoratobag/DdmSpec.scala
- src/test/scala/nl/knaw/dans/easy/fedoratobag/ReadmeSpec.scala
- src/test/scala/nl/knaw/dans/easy/fedoratobag/fixture/EmdSupport.scala
Fixes EASY-2777: cleanup of ABR mapping
* 
* 
> EASY-2777: cleanup of ABR mapping

- src/main/scala/nl/knaw/dans/easy/fedoratobag/DDM.scala
- src/test/scala/nl/knaw/dans/easy/fedoratobag/DdmSpec.scala
Fixes EASY-2794
* Ignore eas:place in combination with eas:point
> EASY-2794: Ignore eas:place in combination with eas:point

- docs/index.md
- src/main/scala/nl/knaw/dans/easy/fedoratobag/Command.scala
- src/main/scala/nl/knaw/dans/easy/fedoratobag/CommandLineOptions.scala
- src/main/scala/nl/knaw/dans/easy/fedoratobag/EasyFedora2vaultApp.scala
- src/main/scala/nl/knaw/dans/easy/fedoratobag/FileFilterType.scala
- src/main/scala/nl/knaw/dans/easy/fedoratobag/FileInfo.scala
- src/main/scala/nl/knaw/dans/easy/fedoratobag/package.scala
- src/test/scala/nl/knaw/dans/easy/fedoratobag/AppSpec.scala
#31 + Only use OpenAccess files for europeana filter
> Fixes for Europeana filter + implemented staging dir for AIPs

- src/main/scala/nl/knaw/dans/easy/fedoratobag/DDM.scala
- src/main/scala/nl/knaw/dans/easy/fedoratobag/filter/DatasetFilter.scala
- src/test/scala/nl/knaw/dans/easy/fedoratobag/DatasetFilterSpec.scala
Fixes EASY-2788: invalid state value in csv
* 
* 
* 
> EASY-2788: invalid state value in csv

- src/main/scala/nl/knaw/dans/easy/fedoratobag/Command.scala
- src/main/scala/nl/knaw/dans/easy/fedoratobag/filter/DatasetFilter.scala
- src/test/scala/nl/knaw/dans/easy/fedoratobag/fixture/EmdSupport.scala
Fixes EASY-
* also have minor refactoring
* 
* 
> NO-JIRA: fedora-version with SIPs, bi-directional isVersionOf check

- docs/index.md
- src/main/scala/nl/knaw/dans/easy/fedoratobag/CommandLineOptions.scala
- src/main/scala/nl/knaw/dans/easy/fedoratobag/DDM.scala
- src/main/scala/nl/knaw/dans/easy/fedoratobag/FileItem.scala
- src/main/scala/nl/knaw/dans/easy/fedoratobag/Spatial.scala
- src/test/scala/nl/knaw/dans/easy/fedoratobag/DdmSpec.scala
- src/test/scala/nl/knaw/dans/easy/fedoratobag/FileItemSpec.scala
Part of EASY-2800
* EASY-2804: jaartal groter dan 19 miljoen
* EASY-2801: Only one ddm:created
> EASY-2800: Improvements to EMD->DDM mapping

- src/main/scala/nl/knaw/dans/easy/fedoratobag/EasyFedoraToBagApp.scala
- src/test/resources/expected-ddm/streaming.xml
- src/test/resources/sample-foxml/streaming.xml
- src/test/scala/nl/knaw/dans/easy/fedoratobag/AppSpec.scala
> fix urn in second bag

- src/main/scala/nl/knaw/dans/easy/fedoratobag/DDM.scala
- src/test/scala/nl/knaw/dans/easy/fedoratobag/DdmSpec.scala
Fixes EASY-2809: ignore empty point/place
* 
* 
* 
> EASY-2809: ignore empty point/place

- src/main/scala/nl/knaw/dans/easy/fedoratobag/filter/FileFilterType.scala
- src/main/scala/nl/knaw/dans/easy/fedoratobag/filter/FileType.scala
- src/main/scala/nl/knaw/dans/easy/fedoratobag/filter/package.scala
- src/test/scala/nl/knaw/dans/easy/fedoratobag/FileInfosSpec.scala
> no original means not originalVersioned

- src/main/scala/nl/knaw/dans/easy/fedoratobag/versions/FedoraVersions.scala
- src/test/scala/nl/knaw/dans/easy/fedoratobag/versions/FedoraVersionsSpec.scala
Fixes DD-343
* Retrieve EMD as Dissemination
> DD-343: Retrieve EMD as Dissemination

- src/main/scala/nl/knaw/dans/easy/fedoratobag/Spatial.scala
- src/test/scala/nl/knaw/dans/easy/fedoratobag/DdmSpec.scala
Fixes DD-394: fix mixed up RD in SpatialPoint
* fix spatial points
* not fix spatial boxes
* 
> DD-394: fix mixed up RD in SpatialPoint

- src/main/scala/nl/knaw/dans/easy/fedoratobag/DDM.scala
- src/main/scala/nl/knaw/dans/easy/fedoratobag/DateMap.scala
- src/test/scala/nl/knaw/dans/easy/fedoratobag/DdmSpec.scala
Fixes DD-409: periods for dates
* 
* 
* 
> DD-409: periods for dates

- src/main/assembly/dist/cfg/logback.xml
- src/main/scala/nl/knaw/dans/easy/fedoratobag/EasyFedoraToBagApp.scala
- src/main/scala/nl/knaw/dans/easy/fedoratobag/FedoraProvider.scala
- src/main/scala/nl/knaw/dans/easy/fedoratobag/FoXml.scala
> NO JIRA ISSSUE: Optimization

- src/main/scala/nl/knaw/dans/easy/fedoratobag/filter/DatasetFilter.scala
- src/test/scala/nl/knaw/dans/easy/fedoratobag/DatasetFilterSpec.scala
Fixes DD-495: drop rule 4 (invalid rights) for strict transformation
* 
* 
* 
> DD-495: drop rule 4 (invalid rights)

- docs/index.md
- src/main/scala/nl/knaw/dans/easy/fedoratobag/Command.scala
- src/main/scala/nl/knaw/dans/easy/fedoratobag/CommandLineOptions.scala
Fixes DD-503
* add an optional input file to `skip` certain datasets
> DD-503: easy-fedora-to-bag --skip-list option

- src/main/scala/nl/knaw/dans/easy/fedoratobag/CommandLineOptions.scala
> NO JIRA ISSUE: no-payload conflicts with original-versioned

- src/test/scala/nl/knaw/dans/easy/fedoratobag/AppSpec.scala
> DD-523: phase 2: fix test of #66

- src/main/scala/nl/knaw/dans/easy/fedoratobag/EasyFedoraToBagApp.scala
- src/test/scala/nl/knaw/dans/easy/fedoratobag/AppSpec.scala
* Update description for non-migrated files
* No bold/href tags allowed, so it is in a CDATA block
* 
* 
> NO EASY: Update description for non-migrated files

- src/main/scala/nl/knaw/dans/easy/fedoratobag/EasyFedoraToBagApp.scala
- src/main/scala/nl/knaw/dans/easy/fedoratobag/FileInfo.scala
- src/main/scala/nl/knaw/dans/easy/fedoratobag/FileItem.scala
- src/main/scala/nl/knaw/dans/easy/fedoratobag/package.scala
- src/test/scala/nl/knaw/dans/easy/fedoratobag/AppSpec.scala
- src/test/scala/nl/knaw/dans/easy/fedoratobag/FileItemSpec.scala
Apply `bagPath` also to the new `originalPath` field.
> fix test for 2nd bag as 1st and only

- src/main/scala/nl/knaw/dans/easy/fedoratobag/FileInfo.scala
- src/test/resources/sample-foxml/inconsistentName.xml
- src/test/scala/nl/knaw/dans/easy/fedoratobag/FileInfosSpec.scala
> DD-556: PR on PR: robust character replacements

- pom.xml
- src/main/scala/nl/knaw/dans/easy/fedoratobag/EasyFedoraToBagApp.scala
- src/main/scala/nl/knaw/dans/easy/fedoratobag/FileInfo.scala
- src/main/scala/nl/knaw/dans/easy/fedoratobag/FileItem.scala
- src/main/scala/nl/knaw/dans/easy/fedoratobag/package.scala
- src/test/resources/sample-foxml/inconsistentName.xml
- src/test/scala/nl/knaw/dans/easy/fedoratobag/AppSpec.scala
- src/test/scala/nl/knaw/dans/easy/fedoratobag/DatasetFilterSpec.scala
- src/test/scala/nl/knaw/dans/easy/fedoratobag/FileInfosSpec.scala
- src/test/scala/nl/knaw/dans/easy/fedoratobag/FileItemSpec.scala
Fixes DD-556
* Specify allowed chars in file path instead of the non-allowed chars
* 
* 
> DD-556: Specify allowed chars in filepath

- src/main/scala/nl/knaw/dans/easy/fedoratobag/EasyFedoraToBagApp.scala
> DD-639: PR on PR: reduced code duplication (Add depositor-info/agreements.xml to second bag)

- src/main/scala/nl/knaw/dans/easy/fedoratobag/EasyFedoraToBagApp.scala
- src/test/scala/nl/knaw/dans/easy/fedoratobag/AppSpec.scala
> DD-623: don't encode cdata block

- docs/index.md
- src/main/scala/nl/knaw/dans/easy/fedoratobag/CommandLineOptions.scala
Fixes NO JIRA ISSUE: help info forgotten with #42
* 
* 
* 
> NO JIRA ISSUE: help info forgotten with #42

- src/main/scala/nl/knaw/dans/easy/fedoratobag/DDM.scala
- src/main/scala/nl/knaw/dans/easy/fedoratobag/filter/DatasetFilter.scala
- src/test/scala/nl/knaw/dans/easy/fedoratobag/DatasetFilterSpec.scala
- src/test/scala/nl/knaw/dans/easy/fedoratobag/DdmSpec.scala
- src/test/scala/nl/knaw/dans/easy/fedoratobag/FileInfosSpec.scala
> DD-810 springfield

- src/main/assembly/dist/cfg/application.properties
- src/main/scala/nl/knaw/dans/easy/fedoratobag/DDM.scala
- src/test/resources/expected-ddm/nonstreaming.xml
- src/test/resources/sample-foxml/nonstreaming.xml
- src/test/scala/nl/knaw/dans/easy/fedoratobag/AppSpec.scala
- src/test/scala/nl/knaw/dans/easy/fedoratobag/DdmSpec.scala
Fixes DD-810 & DD-801
* DD-801 Give OAFRU datasets the dans-license
* Add / Fix tests for DD-810
* 
> DD-810: Add / Fix tests for DD-810
